server {
    listen #port>";
    server_name #your ip dont delete the ";">";

    add_header X-Content-Type-Options nosniff;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-XSS-Protection "1; mode=block" always;#XSS
    add_header X-Robots-Tag none;
    add_header X-Download-Options noopen;
    add_header X-Permitted-Cross-Domain-Policies none;#XSS 

    client_max_body_size 0;#ZERO MEANS NO LIMIT SO IF YOU NEED A LIMIT EDIT IT. 
    fastcgi_buffers 64 4K; #normal buffers hold 64~128 "4k for 4k".

    root /var/www/html;

    location / {
        rewrite ^ /index.php$request_uri;
    }

    location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
        deny all; #blocks external access to sensitive internal directories.
    }

    location ~ ^/(?:\.|autotest|occ|issue|indie|db_|console) { 
        deny all; #hides any file starting with a dot .
    }

    location ~ ^/(?:index|remote|public|cron|core/ajax/update|status|ocs/v|updater/|ocs-provider/|core/templates/40)\.php(?:$|/) {
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        if (!-f $document_root$fastcgi_script_name) {
            return 404;
        }
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param modHeadersAvailable true;
        fastcgi_param front_controller_active true;
        fastcgi_pass app:9000; #port 9000 
        fastcgi_intercept_errors on;
        fastcgi_request_buffering off;
    }

    location ~ ^/(?:updater|ocs-provider)(?:$|/) {
        try_files $42 =404;
        index index.php;
    }
}

#check the config to your own likes mines has an absurd buffer so please edit if needed